CREATE TABLE Menu (
    Menu_ID INT PRIMARY KEY AUTO_INCREMENT,
    Client_ID INT,
    Language VARCHAR(10),
    Menu_Name VARCHAR(100),
    Display_Order INT,
    Parent_Menu_ID INT DEFAULT 0,
    Action VARCHAR(255),
    Header_Message VARCHAR(200),
    FOREIGN KEY (Client_ID) REFERENCES Client(Client_ID) ON DELETE CASCADE
);
INSERT INTO Menu (Menu_ID, Client_ID, Language, Menu_Name, Display_Order, Parent_Menu_ID, Action, Header_Message) VALUES
(1, 1, 'ENG', 'Book Appointment', 1, 0, '', 'Select your preference'),
(2, 1, 'ENG', 'Reschedule', 2, 0, '', ''),
(3, 1, 'ENG', 'Cancel', 3, 0, '', ''),
(4, 1, 'ENG', 'Emergency', 1, 1, '', ''),
(5, 1, 'ENG', 'Tele Consultation', 2, 1, '', ''),
(6, 1, 'ENG', 'Direct Consultation', 3, 1, '', ''),
(7, 1, 'ENG', 'Share Your Location', 1, 4, 'CAPTURE_USER_INPUT', 'Share Your Location'),
(8, 1, 'ENG', 'Enter Name Emergency', 1, 7, 'LIST:EMERGENCY_REASON', 'What is the Emergency'),
(9, 1, 'ENG', 'Confirm Emergency Details', 1, 8, 'CONFIRM', 'Please Confirm Your details'),
(10, 1, 'ENG', 'Finalize Emergency', 1, 9, 'FINALIZE:[MESSAGE TEMPLATE NAME]', 'Waiting for your arrival'),
(11, 1, 'ENG', 'Show Department List', 1, 6, 'LIST:DEPARTMENT', 'Select the Department'),
(12, 1, 'ENG', 'Select Doctor Direct', 1, 11, 'POC:[DEPARTMENT_ID]', 'Select the doctor'),
(13, 1, 'ENG', 'Select Date Direct', 1, 12, 'FETCH_AVAILABLE_DATES_DIRECT', 'Select the date'),
(14, 1, 'ENG', 'Select Time Direct', 1, 13, 'FETCH_AVAILABLE_TIMES_DIRECT', 'Select the time'),
(15, 1, 'ENG', 'Enter Name Direct', 1, 14, 'CAPTURE_USER_INPUT:[NoValidation]', 'Enter Your Name'),
(16, 1, 'ENG', 'Enter Email Direct', 2, 15, 'CAPTURE_USER_INPUT:[emailValidation]', 'Enter Your Email'),
(17, 1, 'ENG', 'Enter Mobile Direct', 3, 16, 'CAPTURE_USER_INPUT:[NumberValidation]', 'Enter Your Phone Number'),
(18, 1, 'ENG', 'Confirm Direct Appointment', 1, 17, 'CONFIRM', 'Please Confirm Your details'),
(19, 1, 'ENG', 'Finalize Direct Appointment', 1, 18, 'FINALIZE:[MESSAGE TEMPLATE NAME]', ''),
(20, 1, 'ENG', 'Select Doctor Tele', 1, 6, '', 'Select a doctor'),
(21, 1, 'ENG', 'Select Date Tele', 1, 20, '', 'Select a date'),
(22, 1, 'ENG', 'Select Time Tele', 1, 21, '', 'Select a time'),
(23, 1, 'ENG', 'Enter Name Tele', 1, 22, '', 'Enter Your Name'),
(24, 1, 'ENG', 'Enter Email Tele', 2, 23, '', 'Enter Your E-Mail'),
(25, 1, 'ENG', 'Enter Mobile Tele', 3, 24, '', 'Enter Your Phone Number'),
(26, 1, 'ENG', 'Enter Location Tele', 1, 25, '', 'Enter Your Location'),
(27, 1, 'ENG', 'Confirm Tele Appointment', 1, 26, '', 'Please Confirm Your details'),
(28, 1, 'ENG', 'Finalize Tele Appointment', 1, 27, '', 'Your gmeet link is given below'),
(29, 1, 'ENG', 'Enter Appointment ID for Reschedule', 1, 3, '', 'Your appointment has been rescheduled'),
(30, 1, 'ENG', 'Enter Appointment ID for Cancel', 1, 4, '', 'Your appointment has been cancelled');
